http:
  routers:
    public:
      rule: 'Host(`reliabletravelph.test`)'
      entryPoints:
        - web
      service: laravel

    admin:
      rule: 'Host(`admin.reliabletravelph.test`)'
      entryPoints:
        - web
      service: laravel

    reverb-public:
      rule: 'Host(`reliabletravelph.test`) && PathPrefix(`/app`)'
      entryPoints:
        - web
      service: reverb
      priority: 100

    reverb-admin:
      rule: 'Host(`admin.reliabletravelph.test`) && PathPrefix(`/app`)'
      entryPoints:
        - web
      service: reverb
      priority: 100

  services:
    laravel:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:8000'

    reverb:
      loadBalancer:
        servers:
          - url: 'http://host.docker.internal:8080'